application: testsdavento
version: 1-0-1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /googlebf512d3ebbc1cfaf\.html
  static_files: static/googlebf512d3ebbc1cfaf.html
  upload: static/googlebf512d3ebbc1cfaf.html
  
- url: /(css|img|js|mvp_1)/(.*)
  static_files: static/\1/\2
  upload: static/(.*)

- url: /_ah/queue/deferred
  script: main.app
  login: admin
 
- url: .*
  script: main.app

  
  
libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"